theme: jekyll-theme-minimal
title: Raphael Avoustin
description: You will find on this page my projects
webrick:
  headers:
    My-Header: Renforcement Learning - 2048
    My-Other-Header: Genetic Algorithm
