theme: jekyll-theme-minimal
title: Raphael Avoustin
description: >-
  Hello, my name is Raphael, and I am a Machine Learning Enthusiast.
  You will find on this web page the projects I've been working on.
